-- Evolui o scaffold inicial para o modelo operacional. Seguro para projetos que já aplicaram 001.
alter type public.order_status rename value 'new' to 'pending';
alter type public.order_status rename value 'accepted' to 'confirmed';
alter table public.categories rename column sort_order to display_order;
alter table public.categories rename column active to is_active;
alter table public.categories add column if not exists description text;
alter table public.products rename column tag to badge;
alter table public.products rename column available to is_available;
alter table public.products rename column sort_order to display_order;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists is_featured boolean not null default false;
alter table public.product_options rename column min_choices to min_selections;
alter table public.product_options rename column max_choices to max_selections;
alter table public.product_options add column if not exists display_order integer not null default 0;
alter table public.product_option_items rename column price_delta to price_modifier;
alter table public.product_option_items rename column available to is_available;
alter table public.product_option_items add column if not exists display_order integer not null default 0;
alter table public.addresses add column if not exists city text not null default 'Campo Mourão';
alter table public.addresses add column if not exists state text not null default 'PR';
alter table public.customers rename column whatsapp to phone;
alter table public.orders rename column number to order_number;
alter table public.orders rename column fulfillment to fulfillment_type;
alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists change_for numeric(10,2);
alter table public.orders add column if not exists idempotency_key uuid unique;
alter table public.order_items rename column product_name to product_name_snapshot;
alter table public.order_items add column if not exists subtotal numeric(10,2) not null default 0;
alter table public.order_item_options rename column option_name to option_name_snapshot;
alter table public.order_item_options rename column item_name to item_name_snapshot;
alter table public.order_item_options rename column price_delta to price_modifier;
alter table public.coupons rename column value to discount_value;
alter table public.coupons rename column max_uses to usage_limit;
alter table public.coupons rename column active to is_active;
alter table public.coupons add column if not exists minimum_order numeric(10,2) not null default 0;
alter table public.delivery_zones rename column active to is_active;
alter table public.business_hours rename column weekday to day_of_week;
alter table public.business_hours rename column opens_at to open_time;
alter table public.business_hours rename column closes_at to close_time;
alter table public.business_hours rename column closed to is_closed;
create table if not exists public.admin_profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in ('owner','manager','staff')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_tracking(id uuid primary key references public.orders(id) on delete cascade,order_number bigint not null,status public.order_status not null,updated_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_profiles where id=auth.uid() and role in ('owner','manager','staff')) $$;
alter table public.admin_profiles enable row level security;alter table public.order_tracking enable row level security;
create policy "admins read own profile" on public.admin_profiles for select to authenticated using(id=auth.uid());
drop policy if exists "public reads catalog" on public.products;
create policy "public reads available products" on public.products for select to anon,authenticated using(active and is_available);
create policy "public reads active promotions" on public.promotions for select to anon,authenticated using(active and starts_at<=now() and ends_at>=now());
create policy "public reads restaurant settings" on public.site_settings for select to anon,authenticated using(key in ('restaurant','accept_orders_when_closed'));
create policy "public reads options" on public.product_options for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.active and p.is_available));
create policy "public reads option items" on public.product_option_items for select to anon,authenticated using(is_available and exists(select 1 from public.product_options po join public.products p on p.id=po.product_id where po.id=option_id and p.active and p.is_available));
create policy "admins manage categories" on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admins manage options" on public.product_options for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admins manage option items" on public.product_option_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admins read customers" on public.customers for select to authenticated using(public.is_admin());
create policy "admins read addresses" on public.addresses for select to authenticated using(public.is_admin());
create policy "public tracks opaque order ids" on public.order_tracking for select to anon,authenticated using(true);
create function public.sync_order_tracking() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.order_tracking(id,order_number,status,updated_at) values(new.id,new.order_number,new.status,now()) on conflict(id) do update set status=excluded.status,updated_at=now();return new;end$$;
create trigger orders_tracking_sync after insert or update of status on public.orders for each row execute function public.sync_order_tracking();
alter publication supabase_realtime add table public.orders;alter publication supabase_realtime add table public.order_tracking;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp','image/avif']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "public reads product images" on storage.objects for select using(bucket_id='product-images');
create policy "admins upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
create policy "admins update product images" on storage.objects for update to authenticated using(bucket_id='product-images' and public.is_admin());
create policy "admins delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());
create index if not exists products_public_menu_idx on public.products(is_available,display_order) where active=true;
create index if not exists orders_created_status_idx on public.orders(created_at desc,status);
select setval(pg_get_serial_sequence('public.orders','order_number'),greatest(coalesce(max(order_number),1046),1046)) from public.orders;
