import {NextResponse} from 'next/server';import {createAdminClient} from '@/lib/supabase/admin';import {createOrderSchema} from '@/lib/orders/schema';import {calculateOrder} from '@/lib/orders/calculate';import {prepareOrderForwarding} from '@/services/order-forwarding';import {restaurant} from '@/data/restaurant';
export async function createOrder(request:Request,orderSource:string="website",bypassHours=false){try{const parsed=createOrderSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Revise os dados do pedido.',fields:parsed.error.flatten().fieldErrors},{status:400});const input=parsed.data;const db=createAdminClient();const {data:duplicate}=await db.from('orders').select('id,order_number,total').eq('idempotency_key',input.idempotencyKey).maybeSingle();if(duplicate)return NextResponse.json({orderId:duplicate.id,orderNumber:duplicate.order_number,total:Number(duplicate.total),forwarding:{mode:'none',external:{enabled:false,reason:'Pedido já registrado.'}}});
 const {data:closedSetting}=await db.from('site_settings').select('value').eq('key','accept_orders_when_closed').maybeSingle();if(!bypassHours&&closedSetting?.value!==true){const formatter=new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false});const parts=Object.fromEntries(formatter.formatToParts().map(x=>[x.type,x.value]));const days:{[key:string]:number}={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};const {data:hours}=await db.from('business_hours').select('*').eq('day_of_week',days[parts.weekday]).single();const time=`${parts.hour}:${parts.minute}:00`;if(!hours||hours.is_closed||time<hours.open_time||time>=hours.close_time)return NextResponse.json({error:`Estamos fechados agora. Abrimos às ${hours?.open_time?.slice(0,5)??'18:30'}.`},{status:409});}
 const calculated=await calculateOrder(db,input);const {data:customer,error:customerError}=await db.from('customers').insert({name:input.customer.name,phone:input.customer.phone}).select('id').single();if(customerError)throw customerError;let addressId:null|string=null;if(input.address){const {data:address,error}=await db.from('addresses').insert({customer_id:customer.id,postal_code:input.address.postalCode,street:input.address.street,number:input.address.number,complement:input.address.complement,district:input.address.district,city:'Campo Mourão',state:'PR',reference:input.address.reference}).select('id').single();if(error)throw error;addressId=address.id;}
 const {data:order,error:orderError}=await db.from('orders').insert({customer_id:customer.id,address_id:addressId,status:'pending',fulfillment_type:input.fulfillmentType,payment_method:input.paymentMethod,subtotal:calculated.subtotal,delivery_fee:calculated.deliveryFee,discount:calculated.discount,total:calculated.total,coupon_code:input.couponCode?.toUpperCase(),change_for:input.changeFor,notes:input.generalNotes,idempotency_key:input.idempotencyKey,order_source:orderSource}).select('id,order_number,total').single();if(orderError)throw orderError;
 for(const line of calculated.lines){const {data:item,error}=await db.from('order_items').insert({order_id:order.id,product_id:line.product.id,product_name_snapshot:line.product.name,unit_price:line.unit,quantity:line.quantity,subtotal:line.subtotal,notes:line.notes}).select('id').single();if(error)throw error;if(line.selected.length){const {error:optionsError}=await db.from('order_item_options').insert(line.selected.map((option)=>({order_item_id:item.id,option_name_snapshot:option.product_options.name,item_name_snapshot:option.name,price_modifier:Number(option.price_modifier)})));if(optionsError)throw optionsError;}}
 const {data:settings}=await db.from('site_settings').select('key,value').in('key',['restaurant','order_forwarding_mode']);const settingMap=Object.fromEntries((settings??[]).map(setting=>[setting.key,setting.value]));const restaurantSetting=settingMap.restaurant as {whatsapp?:string}|undefined;const forwarding=await prepareOrderForwarding({id:order.id,number:order.order_number,customer:input.customer,fulfillmentType:input.fulfillmentType,paymentMethod:input.paymentMethod,changeFor:input.changeFor,address:input.address,lines:calculated.lines.map(line=>({quantity:line.quantity,name:line.product.name,options:line.selected.map(option=>option.name),notes:line.notes})),subtotal:calculated.subtotal,deliveryFee:calculated.deliveryFee,discount:calculated.discount,total:calculated.total,generalNotes:input.generalNotes},restaurantSetting?.whatsapp??restaurant.whatsapp,String(settingMap.order_forwarding_mode??''));return NextResponse.json({orderId:order.id,orderNumber:order.order_number,total:Number(order.total),forwarding},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Não foi possível criar o pedido.'},{status:500});}}

export async function POST(request:Request){return createOrder(request,'website',false)}
